OBJECT_ACTION_DICT = {
    'btn_nav_1': 'mActionPan',
    'btn_nav_2': 'mActionZoomIn',
    'btn_nav_3': 'mActionZoomOut',
    'btn_nav_4': 'mActionZoomFullExtent',
    'btn_nav_5': 'mActionZoomToLayer',
    'btn_nav_6': 'mActionZoomToSelected',
    'btn_nav_7': 'mActionZoomLast',
    'btn_nav_8': 'mActionZoomNext',

    'btn_projekt_1': 'mActionOpenProject',
    'btn_projekt_2': 'mActionNewProject',
    'btn_projekt_3': 'mActionSaveProject',
    'btn_projekt_4': 'mActionSaveProjectAs',

    'btn_attr_1': 'mActionIdentify',
    'btn_attr_2': 'mActionSelectFeatures',
    'zaznacz_panelPushButton': 'mActionSelectFeatures',
    'btn_attr_3': 'mActionDeselectAll',
    'odznacz_panelPushButton': 'mActionDeselectAll',
    'btn_attr_4': 'mActionOpenTable',

    'btn_miary_1': 'mActionMeasure',
    'btn_miary_2': 'mActionMeasureArea',
    'btn_miary_3': 'mActionMeasureAngle',

    'btn_lr_1': 'mActionAddOgrLayer',
    'btn_lr_2': 'mActionAddWmsLayer',
    'btn_lr_3': 'mActionAddPgLayer',
    'btn_lr_4': 'mActionAddRasterLayer',
    'btn_lr_5': 'mActionAddWfsLayer',
    'btn_lr_6': 'mActionAddSpatiaLiteLayer',
    'btn_nowy_wydruk': 'mActionNewPrintLayout',
    'btn_zarzadzanie_wydr': 'mActionShowLayoutManager',

    'btn_vec_1': 'mActionToggleEditing',
    'btn_vec_2': 'mActionSaveLayerEdits',
    'btn_vec_3': 'mActionVertexTool',
    'btn_vec_4': 'mActionUndo',
    'btn_vec_5': 'mActionRedo',
    'btn_vec_6': 'mActionAddFeature',
    'btn_vec_7': 'mActionMoveFeature',
    'btn_vec_8': 'mActionDeleteSelected',
    'btn_vec_9': 'mActionCopyFeatures',
    'btn_vec_10': 'mActionPasteFeatures',
    'btn_vec_12': 'mActionCutFeatures',

    'btn_lab_1': 'mActionLabeling',
    'btn_lab_2': 'mActionChangeLabelProperties',
    'btn_lab_3': 'mActionShowHideLabels',
    'btn_lab_4': 'mActionMoveLabel',
    'btn_lab_5': 'mActionRotateLabel',
    'btn_lab_6': 'mActionDiagramProperties',

    'btn_attr_5': 'mActionMapTips',
    'btn_attr_6': 'mActionNewBookmark',
    'btn_attr_7': 'mActionShowBookmarks',
    'btn_attr_8': 'mActionSelectByExpression',
    'btn_attr_9': 'mActionIdentify',
    'btn_attr_10': 'mActionSelectFeatures',
    'btn_attr_11': 'mActionDeselectAll',
    'btn_attr_12': 'mActionOpenTable',
    'btn_attr_13': 'mActionOpenFieldCalc',
    'btn_attr_14': 'mActionStatisticalSummary',
    'btn_attr_15': 'mActionSelectPolygon',
    'btn_attr_16': 'mActionInvertSelection',

    'btn_dig_5': 'mActionRotateFeature',
    'btn_dig_6': 'mActionSimplifyFeature',
    'btn_dig_7': 'mActionAddRing',
    'btn_dig_8': 'mActionAddPart',
    'btn_dig_9': 'mActionFillRing',
    'btn_dig_10': 'mActionDeleteRing',
    'btn_dig_11': 'mActionDeletePart',
    'btn_dig_12': 'mActionOffsetCurve',
    'btn_dig_13': 'mActionReshapeFeatures',
    'btn_dig_14': 'mActionSplitParts',
    'btn_dig_15': 'mActionSplitFeatures',
    'btn_dig_16': 'mActionMergeFeatureAttributes',
    'btn_dig_17': 'mActionMergeFeatures',
    'btn_dig_18': 'mActionSnappingOptions'
}
